project 'WKImageEditor.xcodeproj'



target 'WKImageEditor' do
  
  pod 'SDWebImage'
  pod 'Masonry'
  
  target 'WKImageEditorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKImageEditorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
